# Generated by Django 5.0.7 on 2024-08-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Spor Ayakkabı', 'Spor'), ('Bot', 'Bot'), ('Terlik', 'Terlik'), ('Sandalet', 'Sandalet'), ('Topuklu Ayakkabı', 'Topuklu'), ('Klasik Ayakkabı', 'Klasik')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('size', models.CharField(max_length=2)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='')),
                ('bestseller', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isHome', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='shoestore.cart')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='shoestore.shoe')),
            ],
        ),
    ]
